# Generated by Django 4.2.29 on 2026-05-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_alter_profile_options_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_history',
            field=models.JSONField(blank=True, default=list, verbose_name='Suhbat tarixi'),
        ),
    ]
