# Generated by Django 4.2.29 on 2026-06-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_profile_chat_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Profil', 'verbose_name_plural': 'Profillar'},
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Oxirgi faollik'),
        ),
    ]
