# Generated by Django 4.2.29 on 2026-06-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_alter_profile_options_profile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255, verbose_name="Qidiruv so'rovi")),
                ('request_count', models.PositiveIntegerField(default=1, verbose_name="So'rovlar soni")),
                ('last_requested', models.DateTimeField(auto_now=True, verbose_name="Oxirgi so'ralgan vaqt")),
            ],
            options={
                'verbose_name': 'Kutilayotgan anime',
                'verbose_name_plural': 'Kutilayotgan animelar',
                'ordering': ['-request_count', '-last_requested'],
            },
        ),
    ]
