# Generated by Django 4.2.29 on 2026-06-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_wantedanime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ban_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Ban sababi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Banned'),
        ),
    ]
