# Generated by Django 4.2.29 on 2026-06-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_profile_ban_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_offended',
            field=models.BooleanField(default=False, verbose_name="Xafa bo'lgan"),
        ),
    ]
